### PR TITLE
0.6.3 (RC1)

### PR DESCRIPTION
**Pull request by karlthepagan**
DOWNLOAD HERE: https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/archive/2017-03-rc1.zip

Release Candidate hotfixes:
#963 
#965 
#966 
#976 
#1078
#1082
#1117

**12 contributors! awesome community participation!**

bugfixes:
* recycler
* remote mining had issues
* pioneers could not travel without vision
* strategy handlers were inconsistent and somewhat confusing
* upgraders were not limited to 15 EPT at RCL8
* uncharging managed containers had issues
* do not pick up minerals without a storage location
* terminal broker will not run if there is no storage
* fix nextRoom selection for robbing

known issues
* creeps will (still) frequently get stuck on borders and say "NOPATH" - block off the exit or build roads as a pathfinding hint, and look for a solution in OCS 0.7.0
* "Corrupt creep without population entry" has not yet been eliminated, but should occur less frequently.

features
* automatic observer activation
* room visuals
* guards may target a border exit to guard both rooms
* military avoiding action
* energy dropping action (onto white/yellow flag)
* unified mining logic
* unified creep predicted renewal/retirement
* extension feeding and move in the same tick
* resource management API (reacllocating overhaul)
* some low bucket CPU throttling
* room.storage.charge - indicates float fraction between configured min and max energy
* travelling action attempts to move to travelPos / travelRoom
* creep.behaviour.ranger.heal is now the standard healing implementation, all creeps try to heal when fleeing and 
* optimized Creep.prototype.hasActiveBodyparts / Creep.prototype.hasBodyparts
* creeps will not try to repair neutral controller rooms
* universal object cloaking (unstable)
* buildNearby and repairNearby will work in reserved, allied and unowned rooms, but not hostile rooms
* pioneers now count against the max number of workers in a room
* upgraders no longer repair their containers, they focus on upgrading
* combat creeps priority targeting can be customized using `priotiryTargetFilter` strategy handler
* many actions now target by closest range, saving CPU
* harvesting prefers closer sources
* major update to reallocating / getNeeds

very important API changes
* Task.installTask, Task.populate
* Room.prototype.placeRoomOrder, Room.prototype.placeReactionOrder, Room.prototype.placeOrder, Room.prototype.setStore, Room.prototype.cancelReactionOrder
* Room.prototype.exits
* FlagDir.flagType

important params
* ROOM_VISUALS: true - enable room visuals
* ROOM_TRADING: true - enable moving energy and resources using terminal
* CONTROLLER_SIGN_UPDATE: true - change your sign message across your whole colony
* MINERS_AUTO_BUILD: true - miners auto-build containers
* REMOTE_RESERVE_HAUL_CAPACITY: 0.2 - wait until remote rooms are at 20% capacity before reserving
* REMOTE_HAULER_MIN_LOAD: 0.9 - remote haulers return home when 90% full
* REMOTE_HAULER_ALLOW_OVER_CAPACITY: 2350 - remote haulers can exceed capacity up to this body size
* PIONEER_UNOWNED: true - build structures in unowned rooms
* DRIVE_BY_REPAIR_RANGE: 1 - do not repair when driving by at long range (saves CPU)
* CRITICAL_BUCKET_LEVEL: 600 - allow CPU bucket to go very low
* CRITICAL_ROLES:  [ 'miner', 'remoteMiner'] - only do source harvesting when CPU is very low
* OBSERVER_OBSERVE_HIGHWAYS_ONLY: false - observers will scan non-highway rooms

### CODE REVIEW

**Comment by karlthepagan** [comment]
Cherry-picked #963 #965 #966

**Comment by Dasku** [comment]
I will run this for 24 hours and provide review after that.

**Comment by chobobobo** [comment]
So after running this for more than 24 hours, I'm seeing low RCL rooms can't spawn reservers because of a change made to task.reserve that sets 2 part reservers as the smallest.

Also seeing a lot of "no path" errors but they seem to resolve themselves somehow over time.

**Comment by karlthepagan** [comment]
A single claim reserver is a new feature I believe. Will investigate.

**Comment by karlthepagan** [comment]
No path errors: I have definitely noticed the absence of traveler.js in this release.

**Comment by chobobobo** [comment]
oh you're right, single claim reserver would be a new feature, ignore that.  The pathing errors I got were related to border swamps I believe.

**Comment by Spedwards** [comment]
@karlthepagan 

> No path errors: I have definitely noticed the absence of traveler.js in this release.

At first I thought you meant you weren't getting errors, but chobobobo's comment earlier ("no path" errors) sheds a little light. Hopefully traveler will get merged soon.

**Comment by karlthepagan** [comment]
`Corrupt creep without population entry!! : worker-800-1`

still getting that, but we've fought this issue for a long time

**Comment by karlthepagan** [comment]
Cherry-picked #976

**Comment by chobobobo** [comment]
DO NOT enable ROUTE_PRECALCULATION in this release, perhaps that parameter should include a warning, the times I've forgotten to set it to false (it's true in my canary builds) I come back to a room with an empty bucket.

**Comment by karlthepagan** [comment]
Must-fix: https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/1048

**Comment by chobobobo** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1078 resolves #1048

**Comment by chobobobo** [comment]
Just noticed that miners won't move to containers blocking single access sources, I will see if I can cherrypick https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1030

**Pull request merged**
