### PR TITLE
patch to avoid statistics for SKs which causes an error

### PR DESCRIPTION
**Pull request by logxen**
This patch addresses internal issue # 185. Fix from georgeberkley.

### CODE REVIEW

**Comment by Spedwards** [comment]
@karlthepagan @logxen I don't think this is the problem. I think it's _any_ hostile in the SK rooms. I've had two instances of getting the JSON error and having regular Invaders in the room.

**Comment by whardeman** [comment]
@karlthepagan was your solution Task.reputation.NPC or something like that?

**Comment by pandabear41** [comment]
This solution doesn't fix anything. Have been running it for a while and I still get the error all the time.

**Comment by whardeman** [comment]
@pandabear41 I think the reality is that this is a generic error that correlates to certain conditions. This fix is for only one of the conditions under which it has been observed.

The error can occur _any time_ self- or circular-referential data is placed into Memory. An example of such came up just yesterday in @Spedwards work on visuals. He was assigning some property (eg `someProp`) to creep.data, then setting another object property equal to creep.data.someProp, then setting creep.data.someProp equal to the new object's someProp. When that happens, it breaks whenever the engine tries to write the creep's data to Memory because it can't serialize the self-reference.

**Comment by Spedwards** [comment]
@whardeman I actually think it was a coincidence. There was an invader in the SK room at the same time I saved the visuals file.

**Comment by karlthepagan** [comment]
I have experienced this while testing dev + traveler.js

The circular reference was resolved only after deleting all of my privateers who were gathering energy.

**Pull request merged**
