### PR TITLE
refactor/roomParts - continue separating room.js

### PR DESCRIPTION
**Pull request by chobobobo**
This breaks out the other fairly easy parts of room.js.

### CODE REVIEW

**Comment by chobobobo** [comment]
Next stage is ready for a look

**Comment by chobobobo** [comment]
Error in this refactor I moved spawns out of room.structures

**Comment by Spedwards** [comment]
Fix for structures:

```javascript
Object.defineProperty(room._structures, 'spawns' {
    configurable: true,
    get: function() {
        // spawn stuff
    }
});
```

I think it's acceptable to access the private field in this way.

**Comment by chobobobo** [comment]
Yeah, that looks like a good compromise for now, I'll look at that again when I do Room.structures.

**Comment by chobobobo** [comment]
Ok, code run and tested for major problems, good to merge.

**Pull request merged**
