### PR TITLE
withdraw energy isn't available until the next tick, so double threshold

### PR DESCRIPTION
**Pull request by karlthepagan**
upgraders are missing a tick every time they withdraw

to fix this double the withdraw threshold

### CODE REVIEW

**Comment by cyberblast** [comment]
Thats why we don't withdraw when it's at 0, but has only 1 last shot

**Comment by karlthepagan** [comment]
I've tested it some time this morning: https://screeps.com/a/#!/history/E49N82?t=16808554

You can see me swap back and forth, sometimes the finishing tick never happens.

**Comment by cyberblast** [comment]
uhm, yes - the creep switching back and forth is the worker right? 
But I didn't see an **upgrader** missing a shot... !?

Upgraders would never move back and forth. even without any energy...

**Comment by karlthepagan** [comment]
no the upgraders missed shots, let's review this live right now

**Comment by cyberblast** [comment]
your container is empty...

**Comment by karlthepagan** [comment]
well, I'll make a gif if you can't test it

**Comment by cyberblast** [comment]
Yes please. I watched your replay a few times now and couldn't see a missing shot :/

**Comment by karlthepagan** [comment]
Failed recently because my upgradder's work count is a divisor of 50.

**Comment by karlthepagan** [comment]
I'm mistaken. Thanks for the closer look.

**Comment by cyberblast** [comment]
no worries

**Pull request closed without merging**
