### PR TITLE
Recycler creep

### PR DESCRIPTION
**Pull request by whardeman**
If you REALLY want to make a creep recycle itself, this is an extremely easy way.

`Game.creeps[<creepName>].data.creepType="recycler";`

### CODE REVIEW

**Comment by karlthepagan** [comment]
Recycler v2 ideas https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/581

**Comment by whardeman** [comment]
Good suggestion 👍

**Comment by cyberblast** [comment]
I don't think we need this. 
You can already do 
`Creep.action.recycling.assign(Game.creeps['<creepName>'])`

**Comment by karlthepagan** [comment]
Assigning recycling fails to complete for several behaviours: upgrader and a few others.

@whardeman also needs to recycle a creep which was mistakenly spawned, so let's make sure that works.

Also see rev 2 ideas. This would be the template behaviour for hauling energy from room to room.

**Comment by cyberblast** [comment]
> Assigning recycling fails to complete for several behaviours: upgrader and a few others.

why?

**Comment by karlthepagan** [comment]
upgraders (and miners?) have a run method which does not check for a currently assigned action.

**Comment by cyberblast** [comment]
Maybe we should fix that instead of developing a new behaviour.

**Comment by whardeman** [comment]
@cyberblast I don't care if we keep it this way, but frankly, in the moment we are struggling through quite a lot of changes, mainly due to the new task systems. I have tried assigning the recycle action from console many, many times because it _is_ obvious. The problem is, it simply doesn't work many times, either due to a race condition, or the creep's own action priority list overrides it. 

If you want to fix it so that assigning the recycle action works 100% of the time, that would be great.

**Comment by cyberblast** [comment]
I didn't know there are issues with assigning recycling, and I'm using it as well.

**Pull request merged**
