### PR TITLE
Checking room controller before spawning second Reserver #522

### PR DESCRIPTION
**Pull request by damintsew**
Checking room controller before spawning second Reserver #522

### CODE REVIEW

**Comment by cyberblast** [comment]
hmm, yes. but then you won't queue a medium claimer 😉 
The reason for the medium queue is, that the low queued doesn't seem get spawned (due to other spawn jobs). Thats why we want to elevate it...

**Comment by damintsew** [comment]
So in this situation will be spawned two Claimers ?
Or it will be evicted from low queue ?

**Comment by cyberblast** [comment]
yes, currently it will keep the first claimer in that low queue, which may eventually spawn as well. 

So the striven solution would be: if the controller is low on reservation and there is a creep for that task in the low queue, then remove that creep from low and put it into medium. 

This way we don't have a problem with 1 spot controllers AND we have that priority elevated.

**Comment by cyberblast** [comment]
closing this one. Implemented in PR #555

**Pull request closed without merging**
