### PR TITLE
coreHits: ranger only heal when you are losing your life

### PR DESCRIPTION
**Pull request by karlthepagan**
this is a major combat strategy change. Accompanied by internal changes.

### CODE REVIEW

**Comment by karlthepagan** [comment]
Looking for testers. Figured out a little bug and fixed it.

**Comment by TafThorne** [comment]
*booming voice* Who dares summon me here!?

Oh right.  Testing some stuff.  I can try and give it a go tomorrow.

**Comment by karlthepagan** [comment]
hullHits and coreHits are going negative for me on a hauler. They should probably be something positive.

**Comment by karlthepagan** [comment]
this hasn't interfered with SK farming

**Pull request merged**
