### PR TITLE
Nuker room object

### PR DESCRIPTION
**Pull request by Dasku**
Prep for adding to fuelling action

### CODE REVIEW

**Comment by Perrytheplatypus43** [comment]
Why did you close this pull request? I am planing to start from here and add a launching system triggered by a flag.

**Comment by Dasku** [comment]
@Perrytheplatypus43 Hi, this has already been implemented in https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/797

**Comment by Perrytheplatypus43** [comment]
Are there any other branches related to nukers?

**Comment by Spedwards** [comment]
See #817 @Perrytheplatypus43

**Pull request closed without merging**
