### PR TITLE
energy bar can be over 100%

### PR DESCRIPTION
**Pull request by karlthepagan**
quick visuals fix, already applied to rc1

### CODE REVIEW

**Comment by Spedwards** [comment]
Wait. How can it be over 100%?

**Comment by karlthepagan** [comment]
it's over 100% when the room has downgraded

**Comment by Spedwards** [comment]
Wouldn't have thought that non-active extensions would count.

**Comment by karlthepagan** [comment]
Also if I remember from taking over a dead room, un-owned extensions are counted but you can't use that energy.

**Pull request merged**
