### PR TITLE
Moving extractor up in priority

### PR DESCRIPTION
**Pull request by Perrytheplatypus43**
Moving the extractor up in priority in be tween road and container.

### CODE REVIEW

**Comment by Spedwards** [comment]
Might I ask the reason for this? It seems like something more for virals.

**Comment by Perrytheplatypus43** [comment]
When i was trying to build my extractor it took forever so thing i should be built faster.

**Comment by Spedwards** [comment]
I'm going to have to disagree with this then. Here are my reasons:

1. Roads get built first to serve creeps walking back and forth to the mineral while building the extractor and container.
2. Container is built second so it's ready as soon as the extractor done.
3. Extractor is one of the lowest priority items in the game. Sure there's only one per room so getting it over and done with is a valid argument, however I don't agree with moving it up.

As stated in my first comment, I'd recommend you move this to a viral.

**Comment by Perrytheplatypus43** [comment]
I thing thoughs are great arguments I will close this pull reqest

**Pull request closed without merging**
