### PR TITLE
Make Level 5 And Long Haul Rooms More Robust

### PR DESCRIPTION
**Pull request by TafThorne**
Level 5 rooms frequently collapse. They are at a sensitive point where the code base switches from non-storage to storage base behaviour and where links are introduced.  If the player does not sequence the construction of these facilities or if one is destroyed it can cause a room to struggle or fail.  

Rooms with long haulage distances from the energy source to the spawn/extension/storage also suffer greatly as we rely heavily on haulers and workers to do the transport of energy.  If there are no working link facilities the workers and haulers can spend all their time hauling energy and recharging the spawn.  In the worst cases they do this at a rate too low to support the continued generation or workers, haulers and miners.

### CODE REVIEW

**Comment by TafThorne** [comment]
As requested by @chobobobo in a slack chat the other day, the above are my changes that make long haul and level 5 rooms more stable.  There should be no net effect on any rooms that have (not got piles of energy laying about) or (lots of incomplete buildings and stored energy).  

I believe this changes are now ready for merging into canary for wider testing.

**Comment by Spedwards** [comment]
You should be merging to `dev` branch. Let @karlthepagan add it to `canary`.

**Comment by TafThorne** [comment]
I thought it was the other way around.  Canary is the brand new stuff and Dev are the bits that are almost ready to be release to Master?  

https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/wiki/OCS-Downloads-and-Branches

Yes, that says:
* Master Branch - Stable
* Development Branch - Mostly Stable
* Canary Branch - Unstable

I read that as _no one_ but special people should merge into **Master** and that should only be done if there is a world ending bug or more normally that things have been tested for quite q while on **Dev**.  A _select few_ should merge into **Dev** as it is code that should be relativly safe, having already been tested a bit on **Canary** however it probably has a few bugs that need fixed.  Anything that is not a bug fix to an existing feature should be merged onto **Canary**, it is where almost all the new code goes and most people should use that as their target for adding code.  

Master <--is upstream of-- Dev <--is upstream of-- Canary

Are you saying that I am incorrect and I should be merging onto Dev, which then gets merge to canary to see if it is OK then it goes back upstream to Dev where it will be decided that it may be ok to go upstream to Master?  

Master <--is upstream of-- Dev <--is upstream of-- Canary <--is upstream of-- Dev  o_O

**Comment by Spedwards** [comment]
Canary is built by a script @karlthepagan runs. It gets `dev` branch and merges in PRs with the `canary` label.

**Comment by TafThorne** [comment]
That being the case what is the point of Canary?  
Either you do development work there or you do not.  
Is it the place to do work if you think what you are doing is high risk?  
What advantage does it give over the system of having to have an individual feature branch? Which is something GitHubs workflow forces on us anyway?

**Comment by TafThorne** [comment]
Spedwards attempted to help by changing my pull request to be off of the Dev branch instead of canary.  It did not got well and he has requested that @karlthepagan takes a look at the issue.  

It might be simplest to abandon the old mess, cherry pick my two changes to a new branch and run the pull request from there.

**Comment by chobobobo** [comment]
Opened #809 for these changes.

**Pull request closed without merging**
