### PR TITLE
0.7.0

### PR DESCRIPTION
**Pull request by karlthepagan**
**10 contributors! Only slightly down from last month's release!**

* Integration of the [BonzAI Traveler API](https://github.com/bonzaiferroni/bonzAI/wiki/Traveler-API)
* travelling action supports many Traveler and border travel options
* Resource management improvements
* programmatic room layout & CYAN flags used for preplanned construction site placement.
* building action will work on allied structures
* bulldozing action will drive over enemy construction sites
* most actions target closest by range
* guards will heal injured creeps in the room
* major reallocating changes
* major robbing changes
* major withdrawing & hauler change: "debounce" prevents most withdrawing / storing infinite cycles
* workers spawned to prevent room collapse have their own behaviour
* labTech behaviour to handle reallocating and reaction fulfillment
* major miner & upgrader changes
* pathfinding avoids most fixed-location workers
* delay spawning of non-critical creeps when CPU bucket is low
* major task validation changes
* fortifying is allowed with less energy in storage

API
* Boosting action (tutorial coming soon)
* objects merge with the parent object when they are "viral'd"
* Action.assign now always validates 2nd argument using isAddableTarget
* OcsMemory: memory segment queue API (using segments 99 and counting down to 90 currently)
* Task: installTask, forceSpawn
* Util class
* FlagDir filter and find changes.
* Creep.assignAction
* Creep.explain() describes what a creep is doing
* Flag.compare, flag.compareTo
* storage.charge
* terminal.charge
* creep setup specifications now accept part count maps
* RoomPosition: radius(), newFlag
* Room.newFlag
* Structure.getNeeds
* room: newFlag(), structures.extensions, powerSpawns.all, nukers.all, structures.my, myConstructionSites, constructionSites now includes hostile, immobileCreeps, structureMatrix, creepMatrix, avoidSKMatrix, showCostMatrix()
* events: Room.costMatrixInvalid

Parameters
* ALL parameters (and other objects) now merge with the parent object when they are "viral'd"
* ACTION_SAY - customize action emojis
* DEBUG_STACKS: true - add stacktrace to every logging statement
* PIONEER_UNOWNED: true - lets pioneers build before claim happens
* PROFILE: true - profile different major OCS execution phases
* REMOVE_CONSTRUCTION_FLAG: false - don't remove CYAN flags after site placed
* REMOTE_HAULER - many remote hauler config options
* ROBBER_REHOME: true - robbers will deliver their haul to a specified room
* SEMI_AUTOMATIC_CONSTRUCTION: false - don't respect CYAN flags
* TRAVELER_STUCK_TICKS: 4 - wait 4 ticks of not moving before re-pathing
* USE_UNBUILT_ROADS: false - don't treat road construction sites as roads
* VISUALS.VISIBLE_ONLY: true - optimize room specific visuals using this user-script: https://github.com/Esryok/screeps-browser-ext/blob/master/visible-room-tracker.user.js
* VISUALS.ACTION_ASSIGNMENT: false - don't draw room visual arrows to indicate action targets

minor changes
* code reloading improvements
* profiling options
* attackController will disengage if the target becomes notHostile (using Task.reputation)
* observer changes
* won't usually attempt to move with no active MOVE parts
* Action.getStrategy convenience method
* change how Setup properties delegate to the list of per-RCL settings
* dismantling works with no carry
* dropping changes
* feeding changes
* invading changes
* picking changes
* storage changes
* uncharging changes
* upgrading changes
* remote worker changes
* reserving changes
* FlagDir.specialFlag() replaces all creep self-targeting in order to avoid circular references
* remote creeps properly recycling on flag removal now

### CODE REVIEW

**Comment by chobobobo** [comment]
Currently testing this code

**Comment by karlthepagan** [comment]
I added the branch 0.7.0-rc2 as well, but that's just useful to notify people who download the zip.

**Comment by karlthepagan** [comment]
I've started 2 new rooms with this RC and I'm pretty satisfied with the roadless workers.

**Comment by karlthepagan** [comment]
@chobobobo final sanity check, I backported #1371

**Comment by karlthepagan** [comment]
you know... yeah these are all things you've been over in great detail, looks good for release I think

**Pull request merged**
