### PR TITLE
update statistics.js to fix buggy email

### PR DESCRIPTION
**Pull request by webremote**
fixes incorrect html for controller with reservation

### CODE REVIEW

**Comment by cyberblast** [comment]
hmm, why? this is the exactly same pattern as for the owned controllers. And it should look the same, no?

**Comment by webremote** [comment]
image

the ones i removed were in fact doubles causing a similar #310

**Comment by cyberblast** [comment]
hmm strange, looks completely different for me. 
Also the resulting HTML should be valid already, no? 

image

**Comment by cyberblast** [comment]
> the ones i removed were in fact doubles causing a similar #310 

No, there you only wrapped the header notification into a div.

**Comment by webremote** [comment]
yes, in this one i fixed the double UL
image

not sure why yours is showing differently, perhaps overriden or your viewer fixes the html or something?

**Comment by webremote** [comment]
hm, now it sends it just right, without the hotfix applied. it's weird.. :/

**Comment by cyberblast** [comment]
hmm, ok. 
I'm going to close the PR, ok? We still have the branch, if we need it again...

**Pull request closed without merging**
