### PR TITLE
Task/lab tech part deux

### PR DESCRIPTION
**Pull request by Dasku**
3rd time's a charm

### CODE REVIEW

**Comment by Dasku** [comment]
Wiki updated here:
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/wiki/Flags

**Comment by chobobobo** [comment]
screen shot 2017-03-26 at 7 31 01 am

labTech's seem to spend a lot of time idling, not sure exactly why.. they also aren't properly filling power

**Comment by Dasku** [comment]
Yep, but thats down to reallocate isnt it? Do you have lab orders? Also nuker fill isnt working atm. So once everything is working correctly and you have lab orders going they will have more to do.

**Comment by chobobobo** [comment]
Yeah, I don't doubt it's an issue with reallocate, but I kind of figured they should be at least charging empty extensions.  I also haven't started using labs so once labs are going they will be busier.

**Pull request merged**
